version: '3.1'

services:

  db:
#    image: postgres
    image: gavinmroy/alpine-postgres
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: tests
      POSTGRES_DB: postgres
    volumes:
      - ./:/docker-entrypoint-initdb.d/
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
    ports:
      - 5432:5432
#    volumes:
#      - D:\pg\:/var/lib/postgresql/data