version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: tests
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - D:\pg\:/var/lib/postgresql/data